spring:
  application:
    name: authorization

server:
  port: 8082

eureka:
  instance:
    secure-port-enabled: @secure-port-enabled@
    non-secure-port-enabled: @non-secure-port-enabled@
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: @eureka.server@

